// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usuthdsminfqguflnzgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzdXRoZHNtaW5mcWd1ZmxuemdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTc3NzYsImV4cCI6MjA2OTM5Mzc3Nn0.L4YQwgbJuI3NUY8Jox4lNrn_BbstDV2nKgmmhjbRiRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});